### ISSUE TITLE
"Persist headers" not working

### ISSUE THREAD

**Issue by robsontenorio** [mll-lab/laravel-graphiql#24] opened 2023-06-23 16:25 UTC
Currently "Persist headers" does not persist the config after page refreshing. Any workarounds?

Tested on Chrome and Safari

![image](https://github.com/mll-lab/laravel-graphiql/assets/118955/dc923e50-b228-4357-b2fb-269c44426a06)

I can see it toggles the variable on local storage, but after page refreshing it is gone.

![image](https://github.com/mll-lab/laravel-graphiql/assets/118955/ec8e0fa9-517e-448f-8124-54b1ea25d6d8)

**Comment by spawnia** [comment] 2023-06-26 07:35
Duplicate of https://github.com/mll-lab/laravel-graphiql/issues/13, related to https://github.com/mll-lab/laravel-graphiql/issues/21.

**Closed by spawnia** 2023-06-26 07:35 UTC
