### ISSUE TITLE
Any way to make graphiql to not open a new tab every time the page reloads?

### ISSUE THREAD

**Issue by JoaoHamerski** [mll-lab/laravel-graphiql#3] opened 2022-10-28 17:07 UTC
If there's something written in the query field and we reload the page, a new tab is openned.

That's completely unecessary and flood the GraphiQL page with `untitled` tabs, is there any way to disable it? I just want one tab openned, if I need more I would like to do it myself.

**Comment by spawnia** [comment] 2022-10-29 18:37
I think this is a duplicate of #2.

**Closed** 2022-10-29 18:37 UTC
